### ISSUE TITLE
Cannot apply shell theme in Gnome running Debian Buster

### ISSUE THREAD

**Issue by KushagraKarira** [StarLabsLtd/StarLabsTheme#4]
![screenshot from 2019-03-06 16-10-26](https://user-images.githubusercontent.com/36698785/53875414-73f8cc80-402a-11e9-8926-c45f6052d5bb.png)

Cannot find the shell theme in gnome.

application, cursor, icons, sound working fine.

there seems to be problem on where shell theme files are copied after installing the package.
it installs in /usr/share/gnome-shell/theme rather than /usr/share/themes.

**Comment by Sean-StarLabs** [comment]
It is intentionally installed to /usr/share/gnome-shell/theme so that when you login with the StarLabs session, the shell theme will be applied.

If you want to use the shell extension, you can just copy the folder to /usr/share/themes but it gets a bit messy if you want things like the lock screen to use the same theme.
